name: Megathread!

on:  
  schedule:
    - cron: '0 0 * * 1'  # every day at midnight
  workflow_dispatch


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate Megathread
      run: |
        python megathread/main.py ${{ secrets.REDDIT_CLIENT_ID }} ${{ secrets.REDDIT_CLIENT_SECRET }} ${{ secrets.REDDIT_USER_AGENT }}
        cat post.md
